name: daily_expense_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # BLoC state management library
  bloc: ^8.1.2 
  # Code generation for BLoC
  build_runner: ^2.4.7 
  # Icons for Cupertino (iOS-style) widgets
  cupertino_icons: ^1.0.2 
  # Integrates Firebase authentication into Flutter apps
  firebase_auth: ^4.15.3
  # Core Flutter Firebase plugin
  firebase_core: ^1.10.6
  # State management library for Flutter
  flutter_bloc: ^8.1.3 
  # Flutter screen adaptation utility
  flutter_screenutil: ^5.9.0
  # Toast notifications for Flutter
  flutter_styled_toast: ^2.2.1 
  # Code generation for immutable classes
  freezed: ^2.4.6 
  freezed_annotation: ^2.4.1 
  # Service locator for dependency injection
  get_it: ^7.6.4 
  # Persistent storage for Flutter
  shared_preferences: ^2.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
