name: daily_expense_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  auth_user:
    path: packages/auth_user
  bloc: ^8.1.2
  build_runner: ^2.4.7
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  db_firestore_client:
    path: packages/db_firestore_client
  db_hive_client:
    path: packages/db_hive_client
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.7
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_speed_dial: ^7.0.0
  flutter_styled_toast: ^2.2.1
  font_awesome_flutter: ^10.6.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path_provider: ^2.1.2
  pattern_formatter: ^3.0.0
  shared_preferences: ^2.2.2
  user_service:
    path: packages/user_service
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
